try {
  $1
} catch (${2:err}) {
  $3
}